title: Shuailin Xue's Homepage
page-top-title: Shuailin Xue
top-section-bg-text: Computer Science
home-subtitle: Shuailin Xue&ensp;|&ensp;薛帅林
copyright-text: '&copy; Sen Li 2023-2025. All Rights Reserved.'
